version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./storage_qdrant:/qdrant/storage
    environment:
      - QDRANT__storage__path=/qdrant/storage
